# -*- coding: utf-8 -*-
"""probelm1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AGQJfZNLypqpuki6b2faD2kqR_VFr9rR
"""

n = int(input())

intervals = []

for _ in range(n):
    start, end = map(int, input().split())
    intervals.append([start, end])

intervals.sort()

merged = []

for start, end in intervals:
    if not merged or start > merged[-1][1]:
        merged.append([start, end])
    else:
        merged[-1][1] = max(merged[-1][1], end)

for start, end in merged:
    print(start, end)